baseURL: https://example.com
languageCode: en-us
title: HOOL.BTC
theme: yourfolio
disableKinds: [RSS, taxonomy, taxonomyTerm]
googleAnalytics: UA-XXXXX-Y

# Menu items
menu:
  main:
  - name: About
    weight: 4
    url: /about
  - name: Contact
    weight: 5
    url: /contact
  - name: Aloha Club
    weight: 1
    url: /alohaclub
  - name: Foto OK
    weight: 2
    url: /fotook
  - name: Gallery
    weight: 3
    url: /gallery

# Custom params
params:
  env: development
  logoImage: img/logo.png
  logoImageAlt: HOOL brand logo